services:
  - type: web
    name: school-management-system
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
    domains:
      - school-management-system.onrender.com

databases:
  - name: school-db
    databaseName: school_management
    user: school_admin
    plan: starter