services:
  - type: web
    name: school-management-system
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: school-management-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: school-management-db
    plan: starter
    databaseName: school_management
    user: admin